[package]
cairo-version = "=2.10.1"
name = "evolute_duel"
version = "1.6.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }
origami_random = { git = "https://github.com/dojoengine/origami" }
origami_rating = { git = "https://github.com/dojoengine/origami" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
achievement = { git = "https://github.com/evolute-studio/arcade" } # fork of arcade https://github.com/cartridge-gg/arcade 
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.4.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.4.0" }
tournaments = { git = "https://github.com/evolute-studio/budokan-tournaments" } # fork of tournaments https://github.com/Provable-Games/tournaments
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
nft_combo = { git = "https://github.com/underware-gg/cairo-nft-combo", tag = "v1.0.0"}

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "tournaments::components::models::game::m_GameMetadata",
    "tournaments::components::models::game::m_TokenMetadata",
    "tournaments::components::models::game::m_GameCounter",
    "tournaments::components::models::game::m_Score",
    "tournaments::components::models::game::m_Settings",
    "tournaments::components::models::game::m_SettingsDetails",
    "tournaments::components::models::game::m_SettingsCounter",
    "tournaments::components::models::tournament::m_Tournament",
    "tournaments::components::models::tournament::m_Registration",
    "tournaments::components::models::tournament::m_Leaderboard",
    "tournaments::components::models::tournament::m_PlatformMetrics",
    "tournaments::components::models::tournament::m_TournamentTokenMetrics",
    "tournaments::components::models::tournament::m_PrizeMetrics",
    "tournaments::components::models::tournament::m_EntryCount",
    "tournaments::components::models::tournament::m_Prize",
    "tournaments::components::models::tournament::m_Token",
    "tournaments::components::models::tournament::m_TournamentConfig",
    "tournaments::components::models::tournament::m_PrizeClaim",
    "tournaments::components::models::tournament::m_QualificationEntries",
    "achievement::events::index::e_TrophyCreation", 
    "achievement::events::index::e_TrophyProgression", 
]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }
assert_macros = "2.10.1"

[profile.provable]

[profile.testing]

[scripts]

upadate_achievements = "sozo execute evolute_duel-game upadate_achievements --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
update_shop = "sozo execute evolute_duel-player_profile_actions update_shop --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"



migrate = "sozo build && sozo migrate"
create_game = "sozo execute evolute_duel-game create_game --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
join_game = "sozo execute evolute_duel-game join_game 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --account-address=0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key=0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b --wait"
make_move1 = "sozo execute evolute_duel-game make_move 1 1 0 7 --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
make_move2 = "sozo execute evolute_duel-game make_move 1 0 2 7 --account-address=0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key=0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b --wait"
make_move3 = "sozo execute evolute_duel-game make_move 1 1 2 6 --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"

make_joker_move1 = "sozo execute evolute_duel-game make_move 0 9 3 0 0 --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
make_joker_move2 = "sozo execute evolute_duel-game make_move 0 14 1 0 1 --account-address=0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key=0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b --wait"

skip_move1 = "sozo execute evolute_duel-game skip_move --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
skip_move2 = "sozo execute evolute_duel-game skip_move --account-address=0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key=0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b --wait"

balance = "sozo execute evolute_duel-player_profile_actions balance --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
username = "sozo execute evolute_duel-player_profile_actions username --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
active_skin = "sozo execute evolute_duel-player_profile_actions active_skin --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
set_balance = "sozo execute evolute_duel-player_profile_actions set_balance 10000 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"

change_username = "sozo execute evolute_duel-player_profile_actions change_username sstr:'player1' --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
change_skin = "sozo execute evolute_duel-player_profile_actions change_skin 1  --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"

create_snapshot = "sozo execute evolute_duel-game create_snapshot 0 2 --account-address=0x17cc6ca902ed4e8baa8463a7009ff18cc294fa85a94b4ce6ac30a9ebd6057c7 --private-key=0x14d6672dcb4b77ca36a887e9a11cd9d637d5012468175829e9c6e770c61642 --wait"
cancel_game_host = "sozo execute evolute_duel-game cancel_game --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
cancel_game_joiner = "sozo execute evolute_duel-game cancel_game --account-address=0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key=0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b --wait"

create_game_from_snapshot = "sozo execute evolute_duel-game create_game_from_snapshot 0 --account-address=0x17cc6ca902ed4e8baa8463a7009ff18cc294fa85a94b4ce6ac30a9ebd6057c7 --private-key=0x14d6672dcb4b77ca36a887e9a11cd9d637d5012468175829e9c6e770c61642 --wait"
join_game_from_snapshot = "sozo execute evolute_duel-game join_game 0x17cc6ca902ed4e8baa8463a7009ff18cc294fa85a94b4ce6ac30a9ebd6057c7 --account-address=0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key=0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b --wait"

create_game1 = "sozo --release execute evolute_duel-game create_game --account-address=0x1f401c745d3dba9b9da11921d1fb006c96f571e9039a0ece3f3b0dc14f04c3d --private-key=0x7230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02 --wait"
cancel_game1 = "sozo --release execute evolute_duel-game cancel_game --account-address=0x1f401c745d3dba9b9da11921d1fb006c96f571e9039a0ece3f3b0dc14f04c3d --private-key=0x7230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02 --wait"


create_tutorial_game = "sozo execute evolute_duel-tutorial create_tutorial_game 0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
make_tutorial_move1 = "sozo execute evolute_duel-tutorial make_move 1 2 3 5 --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"

tournament_initializer = "sozo execute evolute_duel-tournament_mock initializer 0 0 0x00a1e52c51daa10c1a513cd25c261f349aef6b8cad05c0ff066b77f6e99623da 1"
create_tournament = "sozo execute evolute_duel-tournament_mock create_tournament 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec sstr:'Tournament' str:'Tournament Description' 1 20000 31104000 1000 0x04606e04a8dcc7b45cf92f7fb49eca2ec30033e2822d812ae2ebb24e4286f5c5 1 3 0 0x00a1e52c51daa10c1a513cd25c261f349aef6b8cad05c0ff066b77f6e99623da 10 arr:50,20,10 0 10 0 10 1"
get_tournament_id_for_token_id = "sozo call evolute_duel-tournament_mock get_tournament_id_for_token_id 0x04606e04a8dcc7b45cf92f7fb49eca2ec30033e2822d812ae2ebb24e4286f5c5 1"