[package]
cairo-version = "=2.9.2"
name = "evolute_duel"
version = "1.2.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
create_game = "sozo execute evolute_duel-game create_game --account-address=0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --private-key=0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912 --wait"
join_game = "sozo execute evolute_duel-game join_game 0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec --account-address=0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key=0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b --wait"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.0" }
origami_random = { git = "https://github.com/dojoengine/origami" }


[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.0" }
