world_address = "0x6a4d87ac4a224fbc633b46ec896545f8783cfc6d87ce8a4ef8c5630a3c17711"
rpc = "https://api.cartridge.gg/x/liyard-evolute-duel/katana"


[events]
raw = true 
historical = ["evolute_duel-TrophyProgression"]

[indexing]
transactions = true