world_address = "0x0230035e44105bbc11acf2dd1b271a78d53627a810e6a2fb024fd2edcf273c9c"
rpc = "http://localhost:5050/"

[runner]
explorer = true

[events]
raw = true

[indexing]
transactions = true

[sql] 
historical = ["evolute_duel-TrophyProgression"]
