// Generated by dojo-bindgen on Mon, 21 Jul 2025 19:51:39 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::player::Player` model
public class evolute_duel_Player : ModelInstance {
    [ModelField("player_id")]
        public FieldElement player_id;

        [ModelField("username")]
        public FieldElement username;

        [ModelField("balance")]
        public uint balance;

        [ModelField("games_played")]
        public FieldElement games_played;

        [ModelField("active_skin")]
        public byte active_skin;

        [ModelField("role")]
        public byte role;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        