// Generated by dojo-bindgen on Wed, 6 Aug 2025 09:09:36 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `evolute_duel::types::packing::GameMode` enum
public abstract record GameMode() : Enum {
    public record Tutorial() : GameMode;
    public record Ranked() : GameMode;
    public record Casual() : GameMode;
}


// Model definition for `evolute_duel::models::game::GameConfig` model
public class evolute_duel_GameConfig : ModelInstance {
    [ModelField("game_mode")]
        public GameMode game_mode;

        [ModelField("board_size")]
        public byte board_size;

        [ModelField("deck_type")]
        public byte deck_type;

        [ModelField("initial_jokers")]
        public byte initial_jokers;

        [ModelField("time_per_phase")]
        public ulong time_per_phase;

        [ModelField("auto_match")]
        public bool auto_match;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        