// Generated by dojo-bindgen on Wed, 6 Aug 2025 09:09:36 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::game::AvailableTiles` model
public class evolute_duel_AvailableTiles : ModelInstance {
    [ModelField("board_id")]
        public FieldElement board_id;

        [ModelField("player")]
        public FieldElement player;

        [ModelField("available_tiles")]
        public byte[] available_tiles;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        