// Generated by dojo-bindgen on Tue, 29 Jul 2025 12:25:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::migration::MigrationRequest` model
public class evolute_duel_MigrationRequest : ModelInstance {
    [ModelField("guest_address")]
        public FieldElement guest_address;

        [ModelField("controller_address")]
        public FieldElement controller_address;

        [ModelField("requested_at")]
        public ulong requested_at;

        [ModelField("expires_at")]
        public ulong expires_at;

        [ModelField("status")]
        public byte status;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        