// Generated by dojo-bindgen on Wed, 6 Aug 2025 09:09:36 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::player::Player` model
public class evolute_duel_Player : ModelInstance {
    [ModelField("player_id")]
        public FieldElement player_id;

        [ModelField("username")]
        public FieldElement username;

        [ModelField("balance")]
        public uint balance;

        [ModelField("games_played")]
        public FieldElement games_played;

        [ModelField("active_skin")]
        public byte active_skin;

        [ModelField("role")]
        public byte role;

        [ModelField("tutorial_completed")]
        public bool tutorial_completed;

        [ModelField("migration_target")]
        public FieldElement migration_target;

        [ModelField("migration_initiated_at")]
        public ulong migration_initiated_at;

        [ModelField("migration_used")]
        public bool migration_used;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        