// Generated by dojo-bindgen on Tue, 29 Jul 2025 12:25:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::config::CoinConfig` model
public class evolute_duel_CoinConfig : ModelInstance {
    [ModelField("coin_address")]
        public FieldElement coin_address;

        [ModelField("minter_address")]
        public FieldElement minter_address;

        [ModelField("faucet_amount")]
        public BigInteger faucet_amount;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        