// Generated by dojo-bindgen on Tue, 29 Jul 2025 12:25:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::metagame::MetagameBoardBounds` model
public class evolute_duel_MetagameBoardBounds : ModelInstance {
    [ModelField("season_id")]
        public FieldElement season_id;

        [ModelField("min_col")]
        public uint min_col;

        [ModelField("max_col")]
        public uint max_col;

        [ModelField("min_row")]
        public uint min_row;

        [ModelField("max_row")]
        public uint max_row;

        [ModelField("gap_size")]
        public uint gap_size;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        