// Generated by dojo-bindgen on Tue, 29 Jul 2025 12:25:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `core::option::Option` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


// Model definition for `evolute_duel::models::metagame::MetagamePlayerData` model
public class evolute_duel_MetagamePlayerData : ModelInstance {
    [ModelField("season_id")]
        public FieldElement season_id;

        [ModelField("player_address")]
        public FieldElement player_address;

        [ModelField("deck")]
        public byte[] deck;

        [ModelField("tiles_placed")]
        public uint tiles_placed;

        [ModelField("first_tile_placed")]
        public Option<Position> first_tile_placed;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        