// Generated by dojo-bindgen on Wed, 6 Aug 2025 09:09:36 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `core::option::Option` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}

// Type definition for `evolute_duel::types::packing::GameMode` enum
public abstract record GameMode() : Enum {
    public record Tutorial() : GameMode;
    public record Ranked() : GameMode;
    public record Casual() : GameMode;
}

// Type definition for `evolute_duel::types::packing::GameStatus` enum
public abstract record GameStatus() : Enum {
    public record Finished() : GameStatus;
    public record Created() : GameStatus;
    public record Canceled() : GameStatus;
    public record InProgress() : GameStatus;
}


// Model definition for `evolute_duel::models::game::Game` model
public class evolute_duel_Game : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("status")]
        public GameStatus status;

        [ModelField("board_id")]
        public Option<FieldElement> board_id;

        [ModelField("game_mode")]
        public GameMode game_mode;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        