// Generated by dojo-bindgen on Tue, 18 Feb 2025 20:27:59 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `evolute_duel::models::GameState` enum
public abstract record GameState() : Enum {
    public record InProgress() : GameState;
    public record Finished() : GameState;
}

// Type definition for `core::option::Option::<core::felt252>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


// Model definition for `evolute_duel::models::Board` model
public class evolute_duel_Board : ModelInstance {
    [ModelField("id")]
        public FieldElement id;

        [ModelField("initial_edge_state")]
        public byte[] initial_edge_state;

        [ModelField("available_tiles_in_deck")]
        public byte[] available_tiles_in_deck;

        [ModelField("state")]
        public (byte, byte)[] state;

        [ModelField("player1")]
        public FieldElement player1;

        [ModelField("player2")]
        public FieldElement player2;

        [ModelField("last_move_id")]
        public Option<FieldElement> last_move_id;

        [ModelField("game_state")]
        public GameState game_state;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        