// Generated by dojo-bindgen on Wed, 30 Jul 2025 11:43:10 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::scoring::PotentialContests` model
public class evolute_duel_PotentialContests : ModelInstance {
    [ModelField("board_id")]
        public FieldElement board_id;

        [ModelField("potential_contests")]
        public uint[] potential_contests;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        